sudo: false

language: android
jdk: oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.2
    - extra-android-support
    - extra-android-m2repository
  licenses:
     - '.+'

before_install:
  - ./gradlew test

script:
  - sh ci.sh

notifications:
  email: false
  slack: zeta-apps:qHFLKUEiEPtkEypfUSbSgx4R

cache: false
sudo: required